name: untitled1
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

# Dependencies for your Flutter app
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Use a compatible version of the `http` package
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.4+3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Recommended lints for good coding practices

flutter:
  uses-material-design: true # Include Material Icons font for use in the app

  # To add assets to your application, uncomment and use the assets section:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts, uncomment and configure the fonts section:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
